version: 2.1
jobs:
  build:
    docker:
      - image: gradle:alpine
    steps:
      - checkout
      - run: ./gradlew bootJar
      - persist_to_workspace:
          root: ./
          paths:
            - build/
            - .gradle/
  test:
    docker:
      - image: gradle:alpine
    steps:
      - checkout
      - run: ./gradlew test
      - store_test_results:
          path: build/test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test